<?php

/**
 * Implements hook_enable().
 */
function genotypes_loader_enable() {

  // Determine the PostgreSQL version.
  $pg_version = genotypes_loader_recheck_postgresql_version();
  
  drupal_set_message(t('Your postgresql version is: %curr', array('%curr' => $pg_version)));
  
  // If not using PostgreSQL 9.3+, give an error
  if (is_numeric($pg_version)) {
    if ($pg_version < 9.3) {
      drupal_set_message(t('This module requires PostgreSQL 9.3 or higher.'), 'error');
      
      tripal_report_error(
        'genotypes_loader',
        TRIPAL_ERROR,
        'Incompatible postgresql version detected. You are using :curr and this module requires at least 9.3.',
        array( ':curr' => $pg_version )
      );
    }
  } else {
    drupal_set_message(t('Could not determine current version of PostgreSQL. This module requires 9.3 or higher.'), 'error');
    
    tripal_report_error(
      'genotypes_loader',
      TRIPAL_ERROR,
      'Unable to determine postgresql version. You are using :curr and this module requires at least 9.3.',
      array( ':curr' => $pg_version )
    );
  }
  
  
  // Add required terms for loader.

  if (!chado_get_cvterm(['cv_id' => ['name' => 'stock_relationship'], 'name' => 'is_extracted_from'])) {

    chado_insert_cvterm([
      'id' => 'local:is_extracted_from',
      'name' => 'is_extracted_from',
      'cv_name' => 'stock_relationship',
      'definition' => 'Describes a relationship between stocks.  Local term from the genotypes_loader module.'
    ]);
  }
  
  if (!chado_get_cvterm(['cv_id' => ['name' => 'stock_relationship'], 'name' => 'is_marker_of'])) {

    chado_insert_cvterm([
      'id' => 'local:is_marker_of',
      'name' => 'is_marker_of',
      'cv_name' => 'stock_relationship',
      'definition' => 'Local term from the genotypes_loader module.'
    ]);
  }

  if (!chado_get_cvterm(['cv_id' => ['name' => 'feature_property'], 'name' => 'marker_type'])) {
    chado_insert_cvterm([
      'id' => 'local:marker_type',
      'name' => 'marker_type',
      'cv_name' => 'feature_property',
      'definition' => 'Local term from the genotypes_loader module.'
    ]);
  }
  
}

/**
 * Implements hook_install().
 */
function genotypes_loader_install() {

  // Determine the PostgreSQL version.
  $pg_version = genotypes_loader_recheck_postgresql_version();
  
  // If not using PostgreSQL 9.3+, give an error
  if (is_numeric($pg_version)) {
    if ($pg_version < 9.3) {
      drupal_set_message(t('This module requires PostgreSQL 9.3 or higher.'), 'error');
      
      tripal_report_error(
        'genotypes_loader',
        TRIPAL_ERROR,
        'Incompatible postgresql version detected. You are using :curr and this module requires at least 9.3.',
        array( ':curr' => $pg_version )
      );
    }
  } else {
    drupal_set_message(t('Could not determine current version of PostgreSQL. This module requires 9.3 or higher.'), 'error');
    
    tripal_report_error(
      'genotypes_loader',
      TRIPAL_ERROR,
      'Incompatible postgresql version detected. You are using :curr and this module requires at least 9.3.',
      array( ':curr' => $pg_version )
    );
  }
}
